default_platform(:ios)

platform :ios do
  desc "Runs all the tests"
  lane :test do
    test_value = "Hello, world!"
    sh("buildkite-agent", "annotate", "Testing annotation: #{test_value}", "--style", "'info'")
    run_tests(
      device: "iPhone 15",
      scheme: "Highlighter"
    )
  end

  desc "Submit a new beta build to Apple TestFlight"
  lane :beta do
    sync_code_signing(readonly: true)

    # Set the build number to the number of Git commits
    build_number = sh "git log --oneline | wc -l"
    increment_build_number(build_number: build_number)

    # Set the marketing number to the release branch name
    release_branch = ENV['CI_COMMIT_BRANCH'] || ENV['BUILDKITE_BRANCH']
    match = /release\/(.*)/.match(release_branch)
    if match.nil?
      sh("buildkite-agent", "annotate", "Build number: #{build_number}", "--style", "'info'")
    else
      marketing_number = match[1]
      increment_version_number(version_number: marketing_number)
      sh("buildkite-agent", "annotate", "Version: #{marketing_number} (#{build_number})", "--style", "'info'")
    end

    # Build the app for App Store
    build_ios_app(
      cloned_source_packages_path: "SourcePackages",
      export_method: "app-store",
      scheme: "Highlighter")
    
    # Just upload the build to TestFlight, no other changes
    upload_to_testflight(
      api_key_path: ENV["APPLE_API_KEY_JSON"],
      app_platform: "ios",
      skip_submission: true,
      skip_waiting_for_build_processing: true)
  end

  desc "Submit a new beta build to the public TestFlight beta"
  lane :public do
    yesterday = (Date.today - 1).strftime("%Y-%m-%d")
    today = Date.today.strftime("%Y-%m-%d")

    git_log_command = "git log --since=\"#{yesterday}\" --until=\"#{today}\" --pretty=format:\"%s\" --no-merges"
    logs = sh git_log_command

    unless logs.empty?
      upload_to_testflight(
        api_key_path: ENV["APPLE_API_KEY_JSON"],
        app_platform: "ios",
        distribute_only: true,
        distribute_external: true,
        changelog: logs,
        groups: [
          "Public Testers"
        ]
      )
    end
  end

  desc "Set up developer environment"
  lane :dev do
    sync_code_signing(readonly: false)
  end

  desc "Renew signing certs"
  lane :renew do
    sync_code_signing(
      type: "development",
      readonly: false
    )

    sync_code_signing(
      type: "appstore",
      readonly: false
    )
  end
end

platform :mac do
  desc "Runs all the tests"
  lane :test do
    sync_code_signing(platform: "catalyst")
    sync_code_signing
    run_tests(
      scheme: "Highlighter",
      catalyst_platform: "macos")
  end

  desc "Submit a new beta build to Apple TestFlight"
  lane :beta do
    # We MUST sync codesigning twice. The app must be codesigned with
    # a macOS provisioning profile; if it is signed with a Catalyst
    # profile, the embedded Automator action gets an invalid entitlement.
    #
    # However, we need the Catalyst profile for the final export, or the
    # App Store upload will be rejected.
    sync_code_signing
    sync_code_signing(platform: "catalyst")

    # Set the build number to the number of Git commits
    build_number = sh "git log --oneline | wc -l"
    increment_build_number(build_number: build_number)

    # Set the marketing number to the release branch name
    release_branch = ENV['CI_COMMIT_BRANCH'] || ENV['BUILDKITE_BRANCH']
    match = /release\/(.*)/.match(release_branch)
    if match.nil?
      sh("buildkite-agent", "annotate", "Build number: #{build_number}", "--style", "'info'")
    else
      marketing_number = match[1]
      increment_version_number(version_number: marketing_number)
      sh("buildkite-agent", "annotate", "Version: #{marketing_number} (#{build_number})", "--style", "'info'")
    end

    # Build the app for App Store
    build_mac_app(
      export_method: "app-store",
      installer_cert_name: "3rd Party Mac Developer Installer: Cocoatype, LLC (287EDDET2B)",
      scheme: "Highlighter",
      skip_profile_detection: true,
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "com.cocoatype.Highlighter" => "match AppStore com.cocoatype.Highlighter catalyst"
        }
      })

    # Just upload the build to TestFlight, no other changes
    upload_to_app_store(
      api_key_path: ENV["APPLE_API_KEY_JSON"],      
      app_identifier: "com.cocoatype.Highlighter",
      platform: "osx",
      precheck_include_in_app_purchases: false,
      skip_app_version_update: true,
      skip_metadata: true,
      skip_screenshots: true)
  end

  desc "Submit a new beta build to the public TestFlight beta"
  lane :public do
    yesterday = (Date.today - 1).strftime("%Y-%m-%d")
    today = Date.today.strftime("%Y-%m-%d")

    git_log_command = "git log --since=\"#{yesterday}\" --until=\"#{today}\" --pretty=format:\"%s\" --no-merges"
    logs = sh git_log_command

    unless logs.empty?
      upload_to_testflight(
        api_key_path: ENV["APPLE_API_KEY_JSON"],
        app_platform: "osx",
        distribute_only: true,
        distribute_external: true,
        changelog: logs,
        groups: [
          "Public Testers"
        ]
      )
    end
  end

  desc "Set up developer environment"
  lane :dev do
    sync_code_signing(readonly: false)
    sync_code_signing(platform: "catalyst", readonly: false)
  end

  desc "Renew signing certs"
  lane :renew do
    sync_code_signing(
      type: "development",
      readonly: false
    )
    sync_code_signing(
      platform: "catalyst",
      type: "development",
      readonly: false
    )

    sync_code_signing(
      type: "appstore",
      readonly: false
    )
    sync_code_signing(
      platform: "catalyst",
      type: "appstore",
      readonly: false
    )
  end
end
