default_platform(:ios)

platform :ios do
  desc "Runs all the tests"
  lane :test do
    run_tests(scheme: "Highlighter")
  end

  desc "Submit a new beta build to Apple TestFlight"
  lane :beta do
    # Download signing credentials
    get_certificates
    get_provisioning_profile(
      app_identifier: "com.cocoatype.Highlighter",
      filename: "app.mobileprovision",
      platform: "ios")
    get_provisioning_profile(
      app_identifier: "com.cocoatype.Highlighter.Action",
      filename: "action.mobileprovision",
      platform: "ios")
    get_provisioning_profile(
      app_identifier: "com.cocoatype.Highlighter.Photo",
      filename: "photo.mobileprovision",
      platform: "ios")

    # Update the Xcode project with the correct signing credentials
    disable_automatic_code_signing
    update_project_provisioning(
      build_configuration: "Release",
      target_filter: "Highlighter",
      profile: "./app.mobileprovision")
    update_project_provisioning(
      build_configuration: "Release",
      target_filter: "Action",
      profile: "./action.mobileprovision")
    update_project_provisioning(
      build_configuration: "Release",
      target_filter: "Photo",
      profile: "./photo.mobileprovision")

    # Set the build number to the number of Git commits
    build_number = sh "git log --oneline | wc -l"
    increment_build_number(build_number: build_number)

    # Build the app for App Store
    build_app(
      export_method: "app-store",
      scheme: "Highlighter")
    
    # Just upload the build to TestFlight, no other changes
    upload_to_testflight(
      app_platform: "ios",
      skip_submission: true,
      skip_waiting_for_build_processing: true)
  end
end
